export const GET_GAMES = 'GET_GAMES';
export const TEST_ACTION = 'TEST_ACTION';
export const INCREMENT_ID = 'INCREMENT_ID';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_REQUEST_SUCCESS = 'LOGIN_USER_REQUEST_SUCCESS';
export const LOGIN_USER_REQUEST_FAIL = 'LOGIN_USER_REQUEST_FAIL';
export const GET_ALL_USERS_RESPONSE = 'GET_ALL_USERS_RESPONSE';
